module videoShifterLC(
	input clk, // Video Clock (25.175 MHz)
	input clk_sys, // System Clock (65 MHz)
	input [15:0] dataIn, // From Memory
	input loadPixels, // Active high when dataIn is valid pixel data
	output [23:0] pixelOutRGB,

	// CLUT Write Interface
	input clutWrite,
	input [7:0] clutAddr,
	input [23:0] clutData,
	input [1:0] clutByteSel,
	input [7:0] clutByteData,

	input videoBusControl, // Indicates valid data on bus
	input memoryLatch, // Latch strobe

	// Synchronization
	input vsync, // From videoTimerLC (Vid Domain)
	input _hblank // From videoTimerLC (Vid Domain) - Active low during HBlank
);

	// Palette Memory: 256 entries x 24 bits
	reg [23:0] palette [255:0];

	// Write port with Byte Selection for Color
	always @(posedge clk_sys) begin
		if (clutWrite) begin
			if (clutByteSel == 0) palette[clutAddr][23:16] <= clutByteData; // Red
			if (clutByteSel == 1) palette[clutAddr][15:8] <= clutByteData;  // Green
			if (clutByteSel == 2) palette[clutAddr][7:0] <= clutByteData;   // Blue
		end
	end

	// Line Buffer (Dual Port RAM)
	reg [15:0] line_buffer [1023:0];
	reg [9:0] wr_ptr = 0;
	reg [9:0] rd_ptr = 0;

	// Reset pointers on VSync (Sys Domain)
	reg vsync_sys_1, vsync_sys_2;
	always @(posedge clk_sys) begin
		vsync_sys_1 <= vsync;
		vsync_sys_2 <= vsync_sys_1;
	end

	wire vsync_sys_edge = !vsync_sys_1 && vsync_sys_2;

	// Write Logic (Sys Domain)
	// Reset on VSync or maybe per line?
	// We rely on loadPixels gating logic in videoTimerLC which ensures we only write active pixels.
	// But we need to reset wr_ptr per line?
	// If we write 320 words, we must start at 0 next line?
	// We don't have HSync in Sys domain easily.
	// But `loadPixels` is generated by counters reset on line end in Sys domain.
	// So `loadPixels` effectively sequences the writes.
	// However, if we write 0..319, then next line 320..639?
	// We want to reuse buffer space (0..319).
	// Since we don't have a "Line Start" signal in Sys domain input here (only loadPixels),
	// we might need to assume wrapping?
	// 1024 is > 320.
	// Let's reset wr_ptr if we finish a line?
	// Actually, simpler: just let it wrap. 1024 is not multiple of 320.
	// 320 words per line.
	// If we wrap, we are fine as long as read pointer follows.
	// VSync resets both.

	always @(posedge clk_sys) begin
		if (vsync_sys_edge) begin
			wr_ptr <= 0;
		end else if (videoBusControl && memoryLatch && loadPixels) begin
			line_buffer[wr_ptr] <= dataIn;
			wr_ptr <= wr_ptr + 1'b1;
		end
	end

	// Read Logic (Vid Domain)
	reg pixel_sel = 0; // 0=High Byte, 1=Low Byte
	reg [15:0] current_word;

	// Detect VSync edge in Vid Domain
	reg vsync_vid_1;
	always @(posedge clk) vsync_vid_1 <= vsync;
	wire vsync_vid_edge = !vsync && vsync_vid_1;

	// HBlank logic to pause/reset read pointer
	// _hblank is low during blanking.
	// We should only read when _hblank is high (active video).
	// Or we can reset rd_ptr during blanking?
	// If we wrap wr_ptr freely, we must wrap rd_ptr freely.
	// If we reset pointers on VSync, they are aligned.
	// We write N words. We read N words.
	// If we stop reading during HBlank, we stay aligned.
	// Correct!

	always @(posedge clk) begin
		if (vsync_vid_edge) begin
			rd_ptr <= 0;
			pixel_sel <= 0;
		end else if (_hblank) begin // Only advance during active video
			// Pre-fetch word
			current_word <= line_buffer[rd_ptr];

			if (pixel_sel == 1) begin
				pixel_sel <= 0;
				rd_ptr <= rd_ptr + 1'b1;
			end else begin
				pixel_sel <= 1;
			end
		end
	end

	wire [7:0] pixel = (pixel_sel == 0) ? current_word[15:8] : current_word[7:0];

	// Palette Lookup (Read Port)
	reg [23:0] rgb_out;
	always @(posedge clk) begin
		rgb_out <= palette[pixel];
	end

	assign pixelOutRGB = rgb_out;

	// Initial Palette
	integer i;
	initial begin
		for (i=0; i<256; i=i+1)
			palette[i] = {i[7:0], i[7:0], i[7:0]};
	end

endmodule
