`timescale 1ns / 1ps
//============================================================================
//  Macintosh LC - Verilator Simulation Wrapper
//
//  Adapted from MacLC.sv for simulation
//============================================================================

module emu
(
	input         clk_sys,
	input         reset,

	// PS2 keyboard/mouse
	input [10:0]  ps2_key,
	input [24:0]  ps2_mouse,

	// RTC timestamp
	input [32:0]  timestamp,

	// VGA output
	output [7:0]  VGA_R,
	output [7:0]  VGA_G,
	output [7:0]  VGA_B,
	output        VGA_HS,
	output        VGA_VS,
	output        VGA_HB,
	output        VGA_VB,
	output        CE_PIXEL,

	// Audio output
	output [15:0] AUDIO_L,
	output [15:0] AUDIO_R,

	// ROM/disk loading interface (ioctl)
	input         ioctl_download,
	input         ioctl_wr,
	input [24:0]  ioctl_addr,
	input [15:0]  ioctl_dout,
	input [7:0]   ioctl_index,
	output reg    ioctl_wait = 1'b0,

	// SCSI block device interface
	output [31:0] sd_lba[2],
	output [1:0]  sd_rd,
	output [1:0]  sd_wr,
	input  [1:0]  sd_ack,
	input  [7:0]  sd_buff_addr,
	input  [15:0] sd_buff_dout,
	output [15:0] sd_buff_din[2],
	input         sd_buff_wr,
	input  [1:0]  img_mounted,
	input  [63:0] img_size,

	// CPU debug outputs
	output [31:0] debug_pc,
	output [15:0] debug_opcode,
	output        debug_fetch_valid,

	// RAM debug outputs
	output [24:0] debug_ram_addr,
	output [15:0] debug_ram_din,
	output [15:0] debug_ram_dout,
	output        debug_ram_we,
	output        debug_ram_oe,
	output  [1:0] debug_ram_ds,
	output        debug_selectRAM,
	output        debug_selectROM,

	// Peripheral debug outputs
	output        debug_selectVIA,
	output        debug_selectAriel,
	output        debug_selectPseudoVIA,
	output        debug_selectSCSI,
	output        debug_selectSCC,
	output        debug_selectIWM,
	output        debug_selectASC,
	output        debug_selectVRAM,
	output [23:0] debug_cpuAddr,
	output [15:0] debug_cpuDataIn,    // Data from CPU to peripherals
	output [15:0] debug_cpuDataOut,   // Data from peripherals to CPU
	output        debug_cpuRW,        // 1=read, 0=write
	output        debug_cpuBusControl,

	// Machine configuration inputs
	input  [1:0]  cfg_cpuType,      // Unused, kept for sim_main.cpp compatibility
	input         cfg_memSize       // 0=1MB, 1=4MB
);

	localparam SCSI_DEVS = 2;

	// Configuration
	wire      status_mem = cfg_memSize;      // 0=1MB, 1=4MB
	localparam [1:0] status_cpu = 2'b10;     // 68020
	// Mac LC always runs at C15M (~15.67 MHz) - use 16 MHz clock enables

	////////////////////   CLOCKS   ///////////////////

	// Clock generation (clk_sys is 32MHz from testbench)
	wire clk_mem = clk_sys;  // Use same clock for memory
	wire pll_locked = !reset;

	// Clock enables - generated by addrController_top
	wire clk8_en_p, clk8_en_n;
	wire clk16_en_p, clk16_en_n;
	wire clk8;

	// Reset logic
	// NOTE: Do NOT include _cpuReset_o here! The RESET instruction drives
	// reset_n low to reset peripherals, but should NOT reset the CPU itself.
	// IMPORTANT: In simulation, wait for ROM download to complete before releasing reset
	reg n_reset = 0;
	reg n_reset_prev = 0;
	reg dio_download_prev = 0;
	always @(posedge clk_sys) begin
		reg [15:0] rst_cnt;

		if (clk8_en_p) begin
			n_reset_prev <= n_reset;
			dio_download_prev <= dio_download;

			// Debug: track when download completes
			if (dio_download_prev && !dio_download) begin
				$display("SIM: dio_download went LOW - ROM download complete");
			end

			if(~pll_locked || reset || dio_download) begin
				rst_cnt <= '1;
				n_reset <= 0;
			end
			else if(rst_cnt) begin
				rst_cnt <= rst_cnt - 1'd1;
				// Debug: show countdown at key points only
				if (rst_cnt == 16'h0001) begin
					$display("SIM: rst_cnt about to expire, n_reset will go high");
				end
			end
			else begin
				n_reset <= 1;
			end

			// Debug: track when n_reset changes
			if (n_reset != n_reset_prev) begin
				$display("SIM: *** n_reset changed to %b *** (rst_cnt=%04x)", n_reset, rst_cnt);
			end
		end
	end

	///////////////////////////////////////////////////

	assign CE_PIXEL  = 1;

	// Video Output - Mac LC V8 video system
	assign VGA_R  = v8_vga_r;
	assign VGA_G  = v8_vga_g;
	assign VGA_B  = v8_vga_b;
	wire VGA_DE = v8_de;
	assign VGA_VS = v8_vsync;
	assign VGA_HS = v8_hsync;
	assign VGA_HB = v8_hblank;
	assign VGA_VB = v8_vblank;

	wire [10:0] audio;
	assign AUDIO_L = {audio[10:0], 5'b00000};
	assign AUDIO_R = {audio[10:0], 5'b00000};

	// Mac LC memory configuration
	wire [7:0] configRAMSize = 8'h24; // 2MB: no SIMM, 2MB board only
	wire [7:0] pvia_ram_config_out;   // Active RAM config from pseudovia

	// Serial Ports (loopback for sim)
	wire serialOut;
	wire serialIn = serialOut;
	wire serialCTS = 1'b1;
	wire serialRTS;

	// V8 Video system wires
	wire [21:0] v8_video_addr;
	wire v8_hsync, v8_vsync, v8_hblank, v8_vblank, v8_de;
	wire [7:0] v8_vga_r, v8_vga_g, v8_vga_b;
	wire [7:0] ariel_pixel_addr;
	wire [23:0] ariel_palette_data;
	wire [7:0] ariel_reg_dout;
	wire selectAriel;      // From address decoder
	wire selectPseudoVIA;  // From address decoder
	wire selectVRAM;       // From address decoder
	wire [7:0] pseudovia_dout;
	wire pseudovia_irq;
	wire capslock;

	// interconnects
	// CPU
	wire _cpuReset, _cpuReset_o, _cpuUDS, _cpuLDS, _cpuRW, _cpuAS;
	wire _cpuVMA, _cpuVPA, _cpuDTACK;
	wire E_rising, E_falling;
	wire [2:0] _cpuIPL;
	wire [2:0] cpuFC;
	wire [7:0] cpuAddrHi;
	wire [23:0] cpuAddr;
	wire [15:0] cpuDataOut;

	// RAM/ROM
	wire _romOE;
	wire _ramOE, _ramWE;
	wire _memoryUDS, _memoryLDS;
	wire videoBusControl;
	wire dioBusControl;
	wire cpuBusControl;
	wire [22:0] memoryAddr;  // 23-bit SDRAM word address from address controller
	wire [15:0] memoryDataOut;
	wire memoryLatch;
	// Video latch: only pulse when memoryLatch AND in video bus cycle
	wire v8_video_latch = memoryLatch && videoBusControl;
	// peripherals
	wire vid_alt;
	wire memoryOverlayOn, selectSCSI, selectSCC, selectIWM, selectVIA, selectRAM, selectROM;
	wire [15:0] dataControllerDataOut;

	// audio
	wire snd_alt;
	wire loadSound;

	// floppy disk image interface
	wire dskReadAckInt;
	wire [21:0] dskReadAddrInt;
	wire dskReadAckExt;
	wire [21:0] dskReadAddrExt;

	// dtack generation for 16 MHz mode
	reg  dtack_en, cpuBusControl_d;
	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			dtack_en <= 0;
		end
		else begin
			cpuBusControl_d <= cpuBusControl;
			if (_cpuAS) dtack_en <= 0;
			if (!_cpuAS & ((!cpuBusControl_d & cpuBusControl) | (!selectROM & !selectRAM))) dtack_en <= 1;
		end
	end

	assign      _cpuVPA = (cpuFC == 3'b111) ? 1'b0 : ~(!_cpuAS && cpuAddr[23:21] == 3'b111);
	assign      _cpuDTACK = ~(!_cpuAS && cpuAddr[23:21] != 3'b111) | !dtack_en;
	wire        cpu_en_p      = clk16_en_p;
	wire        cpu_en_n      = clk16_en_n;
	assign      _cpuReset_o   = tg68_reset_n;
	assign      _cpuRW        = tg68_rw;
	assign      _cpuAS        = tg68_as_n;
	assign      _cpuUDS       = tg68_uds_n;
	assign      _cpuLDS       = tg68_lds_n;
	assign      E_falling     = tg68_E_falling;
	assign      E_rising      = tg68_E_rising;
	assign      _cpuVMA       = tg68_vma_n;
	assign      cpuFC[0]      = tg68_fc0;
	assign      cpuFC[1]      = tg68_fc1;
	assign      cpuFC[2]      = tg68_fc2;
	assign      cpuAddr[23:1] = tg68_a[23:1];
	assign      cpuDataOut    = tg68_dout;

	wire        tg68_rw;
	wire        tg68_as_n;
	wire        tg68_uds_n;
	wire        tg68_lds_n;
	wire        tg68_E_rising;
	wire        tg68_E_falling;
	wire        tg68_vma_n;
	wire        tg68_fc0;
	wire        tg68_fc1;
	wire        tg68_fc2;
	wire [15:0] tg68_dout;
	wire [31:0] tg68_a;
	wire        tg68_reset_n;
	wire [1:0]  tg68_busstate;

	tg68k tg68k (
		.clk        ( clk_sys      ),
		.reset      ( !_cpuReset ),
		.phi1       ( cpu_en_p  ),
		.phi2       ( cpu_en_n  ),
		.cpu        ( {status_cpu[1], |status_cpu} ),

		.dtack_n    ( _cpuDTACK  ),
		.rw_n       ( tg68_rw    ),
		.as_n       ( tg68_as_n  ),
		.uds_n      ( tg68_uds_n ),
		.lds_n      ( tg68_lds_n ),
		.fc         ( { tg68_fc2, tg68_fc1, tg68_fc0 } ),
		.reset_n    ( tg68_reset_n ),

		.E          (  ),
		.E_div      ( 1'b1 ),
		.E_PosClkEn ( tg68_E_falling ),
		.E_NegClkEn ( tg68_E_rising  ),
		.vma_n      ( tg68_vma_n ),
		.vpa_n      ( _cpuVPA ),

		.br_n       ( 1'b1    ),
		.bg_n       (  ),
		.bgack_n    ( 1'b1 ),

		.ipl        ( _cpuIPL ),
		.berr       ( 1'b0 ),
		.din        ( dataControllerDataOut ),
		.dout       ( tg68_dout ),
		.addr       ( tg68_a ),
		.busstate   ( tg68_busstate )
	);

	// CPU debug - capture PC and opcode during instruction fetch
	// busstate: 00 = fetch code, 10 = read data, 11 = write data, 01 = idle
	reg [31:0] last_fetch_pc;
	reg [15:0] last_fetch_opcode;
	reg        fetch_valid;
	reg        prev_as_n;
	reg [1:0]  prev_busstate;
	reg        as_falling_seen;
	reg [31:0] fetch_addr_latch;

	always @(posedge clk_sys) begin
		if (!n_reset) begin
			fetch_valid <= 0;
			prev_as_n <= 1;
			prev_busstate <= 2'b01;
			as_falling_seen <= 0;
			last_fetch_pc <= 0;
			last_fetch_opcode <= 0;
			fetch_addr_latch <= 0;
		end else begin
			// Default: clear fetch_valid after one cycle
			fetch_valid <= 0;

			// Track AS edges and busstate
			prev_as_n <= tg68_as_n;
			prev_busstate <= tg68_busstate;

			// Latch address when AS goes low during instruction fetch
			if (prev_as_n && !tg68_as_n && tg68_busstate == 2'b00) begin
				fetch_addr_latch <= tg68_a;
				as_falling_seen <= 1;
			end

			// Capture on AS rising edge (bus cycle complete) if this was a fetch
			if (!prev_as_n && tg68_as_n && as_falling_seen && prev_busstate == 2'b00) begin
				last_fetch_pc <= fetch_addr_latch;
				last_fetch_opcode <= dataControllerDataOut;
				fetch_valid <= 1;
				as_falling_seen <= 0;
			end

			// Clear if busstate changes away from fetch before completion
			if (tg68_busstate != 2'b00 && prev_busstate == 2'b00) begin
				as_falling_seen <= 0;
			end
		end
	end

	assign debug_pc = last_fetch_pc;
	assign debug_opcode = last_fetch_opcode;
	assign debug_fetch_valid = fetch_valid;

	// PC-specific debug removed - add back as needed for targeted debugging

	addrController_top ac0
	(
		.clk(clk_sys),
		.clk8(clk8),
		.clk8_en_p(clk8_en_p),
		.clk8_en_n(clk8_en_n),
		.clk16_en_p(clk16_en_p),
		.clk16_en_n(clk16_en_n),
		._cpuReset(_cpuReset),
		.cpuAddr(cpuAddr),
		._cpuUDS(_cpuUDS),
		._cpuLDS(_cpuLDS),
		._cpuRW(_cpuRW),
		._cpuAS(_cpuAS),
		.ram_config(pvia_ram_config_out),
		.memoryAddr(memoryAddr),
		.memoryLatch(memoryLatch),
		._memoryUDS(_memoryUDS),
		._memoryLDS(_memoryLDS),
		._romOE(_romOE),
		._ramOE(_ramOE),
		._ramWE(_ramWE),
		.videoBusControl(videoBusControl),
		.dioBusControl(dioBusControl),
		.cpuBusControl(cpuBusControl),
		.selectSCSI(selectSCSI),
		.selectSCC(selectSCC),
		.selectIWM(selectIWM),
		.selectASC(selectASC),
		.selectVIA(selectVIA),
		.selectRAM(selectRAM),
		.selectROM(selectROM),
		.selectAriel(selectAriel),
		.selectPseudoVIA(selectPseudoVIA),
		.selectVRAM(selectVRAM),
		.v8_video_addr(v8_video_addr),
		.v8_hblank(v8_hblank),
		.v8_vblank(v8_vblank),
		.memoryOverlayOn(memoryOverlayOn),

		.snd_alt(snd_alt),
		.loadSound(loadSound),

		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt)
	);

	wire [1:0] diskEject;
	wire [1:0] diskMotor, diskAct;

	// Video Mode Selection - from PVIA video_config register (bits 2:0 = bpp mode)
	wire [7:0] pvia_video_config;
	wire [7:0] asc_data_out;
	wire asc_irq;

	// Use actual video mode from pseudovia (ROM configures this via register 0x10)
	wire [2:0] v8_video_mode = pvia_video_config[2:0];

	// Monitor ID Selection - 13" RGB
	wire [3:0] v8_monitor_id = 4'h6;

	ariel_ramdac ariel(
		.clk_sys(clk_sys),
		.reset(~n_reset),
		.reg_addr(cpuAddr[10:0]),
		.uds_n(_cpuUDS),
		.lds_n(_cpuLDS),
		.data_in(cpuDataOut[7:0]),
		.data_out(ariel_reg_dout),
		.we(selectAriel && !_cpuRW && cpuBusControl),
		.req(selectAriel && cpuBusControl),

		.pixel_index(ariel_pixel_addr),
		.rgb_out(ariel_palette_data),
		.ariel_written()  // Not used in sim
	);

	// Debug: disabled for now

	pseudovia pvia(
		.clk_sys(clk_sys),
		.reset(~n_reset),
		.addr(cpuAddr[12:0]),
		.data_in(cpuDataOut[7:0]),
		.data_out(pseudovia_dout),
		.we(selectPseudoVIA && !_cpuRW && cpuBusControl),
		.req(selectPseudoVIA && cpuBusControl),
		.vblank_irq(v8_vblank),
		.slot_irq(1'b0),
		.asc_irq(asc_irq),
		.irq_out(pseudovia_irq),
		.ram_config(configRAMSize),
		.monitor_id(v8_monitor_id),
		.video_config(pvia_video_config),
		.ram_config_out(pvia_ram_config_out)
	);

	asc asc_inst(
		.clk(clk_sys),
		.reset(~n_reset),
		.cs(selectASC),
		.addr(cpuAddr[11:0]),
		.data_in(cpuDataOut[7:0]),
		.data_out(asc_data_out),
		.we(!_cpuRW && cpuBusControl),
		.irq(asc_irq)
	);

	maclc_v8_video v8_video(
		.clk_sys(clk_sys),
		.clk8_en_p(clk8_en_p),
		.reset(~n_reset),

		.video_addr(v8_video_addr),
		.video_data_in(ram_do),
		.video_latch(v8_video_latch),

		.video_mode(v8_video_mode),
		.monitor_id(v8_monitor_id),

		.hsync(v8_hsync),
		.vsync(v8_vsync),
		.hblank(v8_hblank),
		.vblank(v8_vblank),
		.vga_r(v8_vga_r),
		.vga_g(v8_vga_g),
		.vga_b(v8_vga_b),
		.de(v8_de),
		.ce_pix(),  // Not used in sim

		.palette_addr(ariel_pixel_addr),
		.palette_data(ariel_palette_data)
	);

	dataController_top #(SCSI_DEVS) dc0
	(
		.clk32(clk_sys),
		.clk8_en_p(clk8_en_p),
		.clk8_en_n(clk8_en_n),
		.E_rising(E_rising),
		.E_falling(E_falling),
		._systemReset(n_reset),
		._cpuReset(_cpuReset),
		._cpuIPL(_cpuIPL),
		.pseudovia_irq(pseudovia_irq),
		._cpuUDS(_cpuUDS),
		._cpuLDS(_cpuLDS),
		._cpuRW(_cpuRW),
		._cpuVMA(_cpuVMA),
		.cpuDataIn(cpuDataOut),
		.cpuDataOut(dataControllerDataOut),
		.cpuAddrRegHi(cpuAddr[12:9]),
		.cpuAddrRegMid(cpuAddr[6:4]),
		.cpuAddrRegLo(cpuAddr[2:1]),
		.selectSCSI(selectSCSI),
		.selectSCC(selectSCC),
		.selectIWM(selectIWM),
		.selectVIA(selectVIA),
		.selectASC(selectASC),
		.asc_data_in(asc_data_out),
		.cpuBusControl(cpuBusControl),
		.videoBusControl(videoBusControl),
		.memoryDataOut(memoryDataOut),
		.memoryDataIn(ram_do),
		.memoryLatch(memoryLatch),
		.selectAriel(selectAriel),
		.ariel_data_in(ariel_reg_dout),
		.selectPseudoVIA(selectPseudoVIA),
		.pseudovia_data_in(pseudovia_dout),

		.ps2_key(ps2_key),
		.capslock(capslock),
		.ps2_mouse(ps2_mouse),
		.serialIn(serialIn),
		.serialOut(serialOut),
		.serialCTS(serialCTS),
		.serialRTS(serialRTS),

		.timestamp(timestamp),

		._hblank(~v8_hblank),
		._vblank(~v8_vblank),
		.vid_alt(vid_alt),

		.audioOut(audio),
		.snd_alt(snd_alt),
		.loadSound(loadSound),

		.insertDisk({dsk_ext_ins, dsk_int_ins}),
		.diskSides({dsk_ext_ds, dsk_int_ds}),
		.diskEject(diskEject),
		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt),
		.diskMotor(diskMotor),
		.diskAct(diskAct),

		.img_mounted(img_mounted),
		.img_size(img_size[40:9]),
		.io_lba(sd_lba),
		.io_rd(sd_rd),
		.io_wr(sd_wr),
		.io_ack(sd_ack),

		.sd_buff_addr(sd_buff_addr),
		.sd_buff_dout(sd_buff_dout),
		.sd_buff_din(sd_buff_din),
		.sd_buff_wr(sd_buff_wr)
	);

	//////////////////////// DOWNLOADING ///////////////////////////

	wire dio_download = ioctl_download;
	wire [23:0] dio_addr = ioctl_addr[24:1];
	wire [7:0] dio_index = ioctl_index;

	// Floppy disk image tracking
	reg dsk_int_ds, dsk_ext_ds;
	reg dsk_int_ss, dsk_ext_ss;
	wire dsk_int_ins = dsk_int_ds || dsk_int_ss;
	wire dsk_ext_ins = dsk_ext_ds || dsk_ext_ss;

	always @(posedge clk_sys) begin
		reg old_down;
		old_down <= dio_download;
		if(old_down && ~dio_download && dio_index == 1) begin
			dsk_int_ds <= (dio_addr == 409600);
			dsk_int_ss <= (dio_addr == 204800);
		end
		if(diskEject[0]) begin
			dsk_int_ds <= 0;
			dsk_int_ss <= 0;
		end
	end

	always @(posedge clk_sys) begin
		reg old_down;
		old_down <= dio_download;
		if(old_down && ~dio_download && dio_index == 2) begin
			dsk_ext_ds <= (dio_addr == 409600);
			dsk_ext_ss <= (dio_addr == 204800);
		end
		if(diskEject[1]) begin
			dsk_ext_ds <= 0;
			dsk_ext_ss <= 0;
		end
	end

	// Download addresses (SDRAM word addresses):
	//   ROM:      $500000 + offset
	//   Floppy 1: $600000 + offset
	//   Floppy 2: $700000 + offset
	reg [22:0] dio_a;
	reg [15:0] dio_data;
	reg        dio_write;
	reg        dio_old_cyc = 0;

	always @(posedge clk_sys) begin
		if(ioctl_wr) begin
			// Don't byte-swap for sim_ram (original swaps for SDRAM byte ordering)
			dio_data <= ioctl_dout;
			case (dio_index[1:0])
				2'b01:   dio_a <= 23'h600000 + {3'b0, dio_addr[19:0]};  // Floppy 1
				2'b10:   dio_a <= 23'h700000 + {3'b0, dio_addr[19:0]};  // Floppy 2
				default: dio_a <= {5'b01010, dio_addr[17:0]};            // ROM at $500000
			endcase
			ioctl_wait <= 1;
		end

		dio_old_cyc <= dioBusControl;
		if(~dioBusControl) dio_write <= ioctl_wait;
		if(dio_old_cyc & ~dioBusControl & dio_write) ioctl_wait <= 0;
	end

	////////////////////////// RAM /////////////////////////////////

	// For simulation with synchronous RAM, use simplified direct download path
	wire download_cycle = dio_download && ioctl_wr;

	// SDRAM word address mapping:
	// memoryAddr[22:0] is already the SDRAM word address from addrController
	// Download path uses dio_a_comb[22:0] directly
	wire [22:0] dio_a_comb;
	assign dio_a_comb = (ioctl_index[1:0] == 2'b01) ? 23'h600000 + {3'b0, ioctl_addr[20:1]} :  // Floppy 1
	                    (ioctl_index[1:0] == 2'b10) ? 23'h700000 + {3'b0, ioctl_addr[20:1]} :  // Floppy 2
	                    {5'b01010, ioctl_addr[18:1]};                                            // ROM at $500000

	wire [24:0] ram_addr = download_cycle ? {2'b00, dio_a_comb[22:0]} :
	                                        {2'b00, memoryAddr[22:0]};



	// Use ioctl_dout directly for download (bypass registered dio_data)
	wire [15:0] ram_din  = download_cycle ? ioctl_dout            : memoryDataOut;
	wire  [1:0] ram_ds   = download_cycle ? 2'b11                 : { !_memoryUDS, !_memoryLDS };
	// Use ioctl_wr directly as write enable during download (bypass registered dio_write)
	wire        ram_we   = download_cycle ? 1'b1                  : !_ramWE;
	wire        ram_oe   = download_cycle ? 1'b0                  : (!_ramOE || !_romOE || dskReadAckInt || dskReadAckExt);
	wire [15:0] ram_do_raw;
	wire [15:0] ram_do   = download_cycle ? 16'hffff : (dskReadAckInt || dskReadAckExt) ? extra_rom_data_demux : ram_do_raw;
	wire [15:0] extra_rom_data_demux = memoryAddr[0] ?
						   {ram_do_raw[7:0],ram_do_raw[7:0]}:{ram_do_raw[15:8],ram_do_raw[15:8]};

	sim_ram ram
	(
		.clk            ( clk_sys     ),
		.reset          ( reset       ),
		.din            ( ram_din     ),
		.addr           ( ram_addr    ),
		.ds             ( ram_ds      ),
		.we             ( ram_we      ),
		.oe             ( ram_oe      ),
		.dout           ( ram_do_raw  )
	);

	// RAM debug outputs
	assign debug_ram_addr = ram_addr;
	assign debug_ram_din = ram_din;
	assign debug_ram_dout = ram_do_raw;
	assign debug_ram_we = ram_we;
	assign debug_ram_oe = ram_oe;
	assign debug_ram_ds = ram_ds;
	assign debug_selectRAM = selectRAM;
	assign debug_selectROM = selectROM;

	// Peripheral debug outputs
	assign debug_selectVIA = selectVIA;
	assign debug_selectAriel = selectAriel;
	assign debug_selectPseudoVIA = selectPseudoVIA;
	assign debug_selectSCSI = selectSCSI;
	assign debug_selectSCC = selectSCC;
	assign debug_selectIWM = selectIWM;
	assign debug_selectASC = selectASC;
	assign debug_selectVRAM = selectVRAM;
`ifdef SIMULATION
	always @(posedge clk_sys) begin
		if (selectPseudoVIA && selectVRAM)
			$display("BUG: selectPseudoVIA AND selectVRAM both active! addr=%h @%0t", cpuAddr, $time);
		if (selectPseudoVIA && !_cpuRW && cpuBusControl)
			$display("PVIA ACTIVE WRITE: cpuAddr=%h data=%h @%0t", cpuAddr, cpuDataOut, $time);
	end
`endif
	assign debug_cpuAddr = cpuAddr;
	assign debug_cpuDataIn = cpuDataOut;  // CPU writes this to peripherals
	assign debug_cpuDataOut = dataControllerDataOut;  // Peripherals send this to CPU
	assign debug_cpuRW = _cpuRW;  // 1=read, 0=write
	assign debug_cpuBusControl = cpuBusControl;

endmodule
