#!/usr/bin/env python3
"""gen_enet_declrom.py — build artifacts from the Apple Ethernet LC TP declROM.

Input: releases/341-0740_AppleLCTwistedPair.BIN (32 KiB, byteLanes $0F = flat).
Verifies provenance (SHA1 + Apple FHeader + rotl1-add CRC) before emitting
anything — a wrong reference must fail loudly, never propagate.

Outputs:
  --hex PATH       verilator/sim_ddr3.v staging image: the card's 64 KiB DDR3
                   ROM window as 8192 x 64-bit hex words (window byte i =
                   guest $FEFF0000+i; the flat ROM occupies +0x8000..+0xFFFF,
                   lower half zero). Byte lane k of word w = window byte 8w+k
                   (the "guest byte A = window byte A" mailbox convention).
  --c-header PATH  span-RLE C header for Main_MiSTer's support/mac staging
                   (the ROM is 99.3% zeros; spans cover the ~331 real bytes).

Usage (from the repo root):
  python scripts/gen_enet_declrom.py --hex verilator/pds_declrom.hex
  python scripts/gen_enet_declrom.py --c-header mac_eth_declrom.h
"""
import argparse
import hashlib
import struct
import sys

EXPECT_SHA1 = "447ce6830600f47f63fdc21dd132539decb76001"  # MAME enetlctp 341-0740.bin
ROM_SIZE = 0x8000
WINDOW_SIZE = 0x10000
ROM_WINDOW_OFF = 0x8000  # guest $FEFF8000


def apple_crc(span, crc_off):
    s = 0
    for i, b in enumerate(span):
        if crc_off <= i < crc_off + 4:
            b = 0
        s = (((s << 1) | (s >> 31)) + b) & 0xFFFFFFFF
    return s


def load_verified(path):
    d = open(path, "rb").read()
    if len(d) != ROM_SIZE:
        sys.exit(f"FATAL: {path} is {len(d)} bytes, expected {ROM_SIZE}")
    sha1 = hashlib.sha1(d).hexdigest()
    if sha1 != EXPECT_SHA1:
        sys.exit(f"FATAL: {path} sha1 {sha1} != expected {EXPECT_SHA1}")
    length, crc = struct.unpack(">II", d[-16:-8])
    testpat = struct.unpack(">I", d[-6:-2])[0]
    bytelanes = d[-1]
    if testpat != 0x5A932BC7 or bytelanes != 0x0F or length != ROM_SIZE:
        sys.exit(f"FATAL: FHeader mismatch (testPattern={testpat:08x} "
                 f"byteLanes={bytelanes:02x} length={length:08x})")
    span = d[len(d) - length:]
    computed = apple_crc(span, len(span) - 12)
    if computed != crc:
        sys.exit(f"FATAL: Apple CRC {computed:08x} != stored {crc:08x}")
    return d


def emit_hex(rom, path):
    win = bytearray(WINDOW_SIZE)
    win[ROM_WINDOW_OFF:ROM_WINDOW_OFF + ROM_SIZE] = rom
    with open(path, "w", newline="\n") as f:
        for w in range(WINDOW_SIZE // 8):
            chunk = win[w * 8:w * 8 + 8]
            f.write("".join(f"{b:02x}" for b in reversed(chunk)) + "\n")
    print(f"wrote {path}: {WINDOW_SIZE // 8} words")


def emit_c_header(rom, path):
    # non-zero spans, merging gaps < 16 zero bytes
    spans = []
    i = 0
    while i < len(rom):
        if rom[i] == 0:
            i += 1
            continue
        j = i
        gap = 0
        end = i
        while j < len(rom):
            if rom[j] != 0:
                end = j + 1
                gap = 0
            else:
                gap += 1
                if gap >= 16:
                    break
            j += 1
        spans.append((i, end - i))
        i = end
    blob = b"".join(rom[o:o + n] for o, n in spans)
    with open(path, "w", newline="\n") as f:
        f.write("// Generated by scripts/gen_enet_declrom.py (MacLC_MiSTer) from the\n")
        f.write("// Apple Ethernet LC Twisted Pair declROM 341-0740 (820-0532-B).\n")
        f.write(f"// sha1 {EXPECT_SHA1}; span-RLE: zero-fill the window, then play spans.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define MAC_ETH_DECLROM_SIZE 0x{ROM_SIZE:x}\n")
        f.write(f"#define MAC_ETH_DECLROM_WINDOW_OFF 0x{ROM_WINDOW_OFF:x}\n\n")
        f.write("static const struct { uint16_t off; uint16_t len; } "
                f"mac_eth_declrom_spans[{len(spans)}] = {{\n")
        for o, n in spans:
            f.write(f"\t{{ 0x{o:04x}, 0x{n:04x} }},\n")
        f.write("};\n\n")
        f.write(f"static const uint8_t mac_eth_declrom_data[{len(blob)}] = {{\n")
        for k in range(0, len(blob), 12):
            f.write("\t" + ", ".join(f"0x{b:02x}" for b in blob[k:k + 12]) + ",\n")
        f.write("};\n")
    print(f"wrote {path}: {len(spans)} spans, {len(blob)} data bytes")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default="releases/341-0740_AppleLCTwistedPair.BIN")
    ap.add_argument("--hex")
    ap.add_argument("--c-header")
    a = ap.parse_args()
    rom = load_verified(a.rom)
    if not a.hex and not a.c_header:
        sys.exit("nothing to do: pass --hex and/or --c-header")
    if a.hex:
        emit_hex(rom, a.hex)
    if a.c_header:
        emit_c_header(rom, a.c_header)


if __name__ == "__main__":
    main()
